# Exemplo futuro para subdomínios
# server_name *.olivererp.com olivererp.com;
# location / {
#   proxy_pass http://core-client:5173;
# }
# location /api/ {
#   proxy_pass http://core-server:3001;
# }
